### ISSUE TITLE
Redirect for React Router v4

### ISSUE THREAD

**Issue by scyclow** [rafrex/react-github-pages#1]
React Router 4 has an entirely different API, where the `Match` component doesn't seem to have an `onEnter` hook. Any idea how to handle a redirect here? It seems like `Match` can take a `render` function that works somewhat similarly.

**Comment by rafgraph** [comment]
@scyclow `react-github-pages` has been deprecated in favor of [`spa-github-pages`](https://github.com/rafrex/spa-github-pages), which works independent of `react-router`.
